services:
  web:
    image: luligu/matterbridge:latest
    container_name: twilight-matterbridge
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/plugins:/root/Matterbridge
      - ${APP_DATA_DIR}/data/storage:/root/.matterbridge
      - ${APP_DATA_DIR}/data/certs:/root/.mattercert
